--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIMS ALL WARRANTIES
-- WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY
-- SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
-- RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
-- NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE
-- USE OR PERFORMANCE OF THIS SOFTWARE.
--

ALTER TABLE "FOREST"."PERSON_GROUPS" DROP CONSTRAINT FK_PERSON_GROUPS_PERSON
ALTER TABLE "FOREST"."PERSON_GROUPS" DROP CONSTRAINT FK_PERSON_GROUPS_GROUPS
ALTER TABLE "FOREST"."CUSTOMER_ORDER" DROP CONSTRAINT FK_CUSTOMER_ORDER_ORDER_STATUS1
ALTER TABLE "FOREST"."CUSTOMER_ORDER" DROP CONSTRAINT FK_CUSTOMER_ORDER_CUSTOMER1
ALTER TABLE "FOREST"."PRODUCT" DROP CONSTRAINT FK_PRODUCT_CATEGORY
ALTER TABLE "FOREST"."ORDER_DETAIL" DROP CONSTRAINT FK_ORDER_DETAIL_PRODUCT
ALTER TABLE "FOREST"."ORDER_DETAIL" DROP CONSTRAINT FK_ORDER_DETAIL_ORDER

DROP TABLE "FOREST"."PERSON_GROUPS"
DROP TABLE "FOREST"."PERSON"
DROP TABLE "FOREST"."GROUPS"
DROP TABLE "FOREST"."ORDER_DETAIL"
DROP TABLE "FOREST"."CUSTOMER_ORDER"
DROP TABLE "FOREST"."ORDER_STATUS"
DROP TABLE "FOREST"."PRODUCT"
DROP TABLE "FOREST"."CATEGORY"